common_tags:
  Program: MyLab
  Owner: smithdavid
  Department: "US CS FSI COGS"

core_tags:
  Environment: "Core"

prod_tags:
  Environment: "Prod"

dev_tags:
  Environment: "Dev"

adds:
  ussc-adds-ip_address: ["10.0.0.68"] # Add more IP addresses to create more domain controllers
  euw-adds-ip_address: ["10.1.0.68"] # Add more IP addresses to create more domain controllers
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2019-Datacenter
  version: latest
  vm_size: Standard_B2s
  admin_username: azadmin

ckalab:
  ussc-ckalab-ip_address: ["10.0.4.4", "10.0.4.5", "10.0.4.6", "10.0.4.7"] # Add more IP addresses to create more domain controllers
  publisher: OpenLogic
  offer: CentOS
  sku: 7.7
  version: latest
  vm_size: Standard_Ds2_v2
  admin_username: azroot

loganalytics:
  monitor_solutions:
    [
      ADReplication,
      ADAssessment,
      AntiMalware,
      AgentHealthAssessment,
      Updates,
      NetworkMonitoring,
      KeyVaultAnalytics,
      ServiceDesk,
      AzureActivity,
      AzureAutomation,
      AzureSQLAnalytics,
      ChangeTracking,
      Security,
    ]
