common_tags:
  Program: MyLab
  Owner: "smithdavid"
  Department: "US CS FSI COGS"

core_tags:
  Environment: "Core"

prod_tags:
  Environment: "Prod"

dev_tags:
  Environment: "Dev"

monitor_solutions:
  [
    "ADReplication",
    "AntiMalware",
    "AgentHealthAssessment",
    "Updates",
    "NetworkMonitoring",
    "KeyVaultAnalytics",
    "ServiceDesk",
    "AzureActivity",
    "AzureAutomation",
    "AzureBackup",
    "AzureSQLAnalytics",
    "ChangeTracking",
    "Security",
  ]
