common_tags:
  Program: MyLab
  Owner: smithdavid
  Department: "US CS FSI COGS"

core_tags:
  Environment: "Core"

prod_tags:
  Environment: "Prod"

dev_tags:
  Environment: "Dev"

adds:
  ussc-adds-ip_address: ["10.0.0.68", "10.0.0.69"] # Add more IP addresses to create more domain controllers
  euw-adds-ip_address: ["10.1.0.68", "10.1.0.69"] # Add more IP addresses to create more domain controllers
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2019-Datacenter
  version: latest
  vm_size: Standard_B1s
  admin_username: azadmin
  monitor_solutions:
    [
      ADReplication,
      ADAssessment,
      AntiMalware,
      AgentHealthAssessment,
      Updates,
      NetworkMonitoring,
      KeyVaultAnalytics,
      ServiceDesk,
      AzureActivity,
      AzureAutomation,
      AzureSQLAnalytics,
      ChangeTracking,
      Security,
    ]
